const CLUBS = [
  ['Atalanta','ATA','#166534'],['Bologna','BOL','#b91c1c'],['Cagliari','CAG','#1d4ed8'],['Como','COM','#2563eb'],['Cremonese','CRE','#dc2626'],['Fiorentina','FIO','#7e22ce'],['Genoa','GEN','#be123c'],['Inter','INT','#155eaa'],['Juventus','JUV','#252525'],['Lazio','LAZ','#0ea5e9'],['Lecce','LEC','#eab308'],['Milan','MIL','#c81e1e'],['Napoli','NAP','#199ad6'],['Parma','PAR','#f5c518'],['Pisa','PIS','#1d4ed8'],['Roma','ROM','#8f1d21'],['Sassuolo','SAS','#15803d'],['Torino','TOR','#7f1d1d'],['Udinese','UDI','#52525b'],['Verona','VER','#1e3a8a']
].map((c,i)=>({name:c[0],code:c[1],color:c[2],news:3+(i*7)%14,breaking:i%7===0,updated:`${7+(i%4)}:${String((i*13)%60).padStart(2,'0')}`}));

const NEWS = [
  {id:1,club:'Napoli',type:'Official',title:'Allenamento mattutino: lavoro personalizzato per il terzino',summary:'Il report del club segnala gestione dei carichi. Nuova valutazione prevista nella rifinitura.',source:'SSC Napoli',time:2,score:96,topic:'Injuries'},
  {id:2,club:'Inter',type:'Reported',title:'Possibile rotazione a centrocampo nella prossima gara',summary:'Due fonti concordano su un cambio rispetto all’ultima formazione utilizzata.',source:'Gazzetta Demo',time:4,score:84,topic:'Probable XI'},
  {id:3,club:'Milan',type:'Rumour',title:'Primi contatti esplorativi per il rinnovo del difensore',summary:'Scenario preliminare non confermato dal club; attendere riscontri ufficiali.',source:'Mercato Demo',time:7,score:61,topic:'Players'},
  {id:4,club:'Roma',type:'Official',title:'Conferenza pre-partita programmata per le 14:00',summary:'L’allenatore parlerà dal centro sportivo alla vigilia del match.',source:'AS Roma',time:9,score:91,topic:'Match'},
  {id:5,club:'Juventus',type:'Reported',title:'Prove tattiche con linea difensiva a quattro',summary:'Indicazione riportata da tre osservatori presenti nella sessione aperta.',source:'Tuttosport Demo',time:16,score:79,topic:'Tactics'},
  {id:6,club:'Atalanta',type:'Official',title:'Rientro parziale in gruppo per il centrocampista',summary:'Il giocatore ha svolto la prima parte della seduta con i compagni.',source:'Atalanta BC',time:28,score:94,topic:'Injuries'},
  {id:7,club:'Bologna',type:'Reported',title:'Cresce la fiducia per il recupero dell’attaccante',summary:'La decisione sulla convocazione arriverà dopo il test di domani.',source:'Corriere Demo',time:51,score:76,topic:'Injuries'},
  {id:8,club:'Fiorentina',type:'Rumour',title:'Osservatori esteri attesi per il giovane esterno',summary:'Segnalazione a bassa confidenza, non risultano offerte formali.',source:'Network Demo',time:80,score:48,topic:'Players'}
];

const PLAYERS = [
  ['Riccardo Orsolini','Bologna','Winger','8.1','Monitor'],['Nicolò Barella','Inter','Midfielder','8.7','Key'],['Scott McTominay','Napoli','Midfielder','8.4','Key'],['Kenan Yıldız','Juventus','Forward','8.0','Rising'],['Matías Soulé','Roma','Winger','7.8','Monitor'],['Éderson','Atalanta','Midfielder','8.3','Key'],['Rafael Leão','Milan','Winger','8.2','Key'],['Moise Kean','Fiorentina','Forward','8.0','Rising']
];

const NAV = [
  ['Overview',[['home','⌂','Home'],['clubs','⬢','Squadre'],['brief','☀','Morning Brief']]],
  ['Intelligence',[['news','▤','News Feed'],['match','◆','Match Intelligence'],['injuries','✚','Injuries'],['lineup','⬡','Probable XI'],['players','◉','Players']]],
  ['Workspace',[['watchlist','☆','Watchlist'],['sources','◌','Sources'],['archive','□','Archive']]]
];

const state = {route:location.hash.slice(1)||'home',filter:'All',hours:'24',club:null,watchlist:JSON.parse(localStorage.getItem('spi-watchlist')||'[]')};
let automationStatus = {generatedAt:null,mode:'demo',status:'ready',message:'Dataset demo attivo.',sourcesChecked:0,sourcesSucceeded:0,sourcesFailed:0};
const app=document.querySelector('#app');
const fmtType=t=>t.toLowerCase();
const clubByName=n=>CLUBS.find(c=>c.name===n);
const visibleNews=()=>NEWS.filter(n=>(state.hours==='all'||n.time<=Number(state.hours))&&(state.filter==='All'||n.type===state.filter||n.topic===state.filter));
const logo=c=>`<span class="club-logo" style="box-shadow:inset 0 -4px 0 ${c.color}">${c.code}</span>`;
const badge=t=>`<span class="tag ${fmtType(t)}">${t}</span>`;

function renderNav(){
  mainNav.innerHTML=NAV.map(([group,items])=>`<div class="nav-group-label">${group}</div>${items.map(([id,icon,label])=>`<button class="nav-item ${state.route===id?'active':''}" data-route="${id}"><span class="nav-icon">${icon}</span>${label}${id==='watchlist'&&state.watchlist.length?`<span class="nav-count">${state.watchlist.length}</span>`:''}</button>`).join('')}`).join('');
}
function head(kicker,title,sub=''){return `<div class="page-head"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1>${sub?`<p class="subhead">${sub}</p>`:''}</div><div class="updated">Aggiornato oggi, 08:42<br>Fuso orario Europe/Rome</div></div>`}
function newsItem(n){let source=n.source.replace('SSC Napoli','Fonte ufficiale demo').replace('AS Roma','Fonte ufficiale demo').replace('Atalanta BC','Fonte ufficiale demo').replace('Gazzetta Demo','Testata nazionale demo').replace('Tuttosport Demo','Testata nazionale demo').replace('Corriere Demo','Testata locale demo').replace('Mercato Demo','Fonte mercato demo').replace('Network Demo','Fonte mercato demo');return `<article class="news-item" data-news="${n.id}"><div class="source-label">${source}</div><div class="news-meta">${badge(n.type)}<span>${n.club}</span><span>·</span><span>${n.time}h fa</span><span class="score"><strong>${n.score}</strong>/100 relevance</span></div><h3>${n.title}</h3><p>${n.summary}</p></article>`}

function home(){return `${head('Daily command center','Buongiorno, Federico.','Le informazioni essenziali della mattina, ordinate per affidabilità e impatto.')}
<section class="grid metrics"><div class="card metric"><div class="metric-label">Articoli analizzati</div><div class="metric-value">247</div><div class="metric-delta">+31 dall’ultimo briefing</div></div><div class="card metric"><div class="metric-label">Fonti monitorate</div><div class="metric-value">38</div><div class="metric-delta">92% operative</div></div><div class="card metric"><div class="metric-label">Segnali ad alta priorità</div><div class="metric-value">12</div><div class="metric-delta">3 richiedono verifica</div></div><div class="card metric"><div class="metric-label">Club aggiornati</div><div class="metric-value">20/20</div><div class="metric-delta">Copertura completa</div></div></section>
<section class="grid dashboard-grid"><div class="stack"><div class="card"><div class="section-head"><h2>Morning Brief</h2><button class="link-btn" data-route="brief">Apri briefing →</button></div><div class="brief-lead"><h2>Infortuni e rotazioni dominano il quadro pre-gara</h2><p>Quattro club segnalano gestione individuale dei carichi. Napoli e Bologna sono i dossier con maggiore variazione nelle ultime 12 ore.</p></div><div class="signal-list"><div class="signal"><span class="signal-icon">✚</span><span><b>6 aggiornamenti medici</b><small>2 ufficiali · 4 riportati</small></span><span>→</span></div><div class="signal"><span class="signal-icon">⬡</span><span><b>3 probabili formazioni aggiornate</b><small>Consensus medio: 78%</small></span><span>→</span></div></div></div><div class="card"><div class="section-head"><h2>Ultime intelligence</h2><button class="link-btn" data-route="news">Vedi feed →</button></div>${visibleNews().slice(0,4).map(newsItem).join('')}</div></div>
<aside class="stack"><div class="card"><div class="section-head"><h2>Source Consensus</h2><span class="tag official">Live demo</span></div><p class="subhead">Convergenza tra fonti indipendenti nelle ultime 24 ore.</p>${[['Infortuni Napoli',4,5],['Assetto Juventus',3,5],['Rinnovo Milan',2,5]].map(x=>`<div style="margin-top:16px"><div class="news-meta"><b style="color:var(--text)">${x[0]}</b><span class="score">${x[1]}/${x[2]}</span></div><div class="consensus" style="margin-top:7px">${Array.from({length:x[2]},(_,i)=>`<i class="${i<x[1]?'on':''}"></i>`).join('')}</div></div>`).join('')}</div><div class="card"><div class="section-head"><h2>Aggiornamento automatico</h2><span class="status-dot"></span></div><p class="subhead">${automationStatus.message}</p><div class="signal-list"><div class="signal"><span class="signal-icon">↻</span><span><b>Ogni giorno alle 06:00</b><small>Europe/Rome · GitHub Actions</small></span></div><div class="signal"><span class="signal-icon">${automationStatus.sourcesSucceeded}</span><span><b>${automationStatus.sourcesChecked} fonti controllate</b><small>${automationStatus.sourcesFailed} errori nell’ultimo ciclo</small></span></div></div><button class="primary-btn" style="margin-top:14px" data-toast="Per aggiornare subito: GitHub → Actions → Run workflow">Aggiorna ora</button></div><div class="card"><div class="section-head"><h2>Breaking monitor</h2><span class="pulse"></span></div><div class="signal"><span class="signal-icon">!</span><span><b>Napoli · Medical</b><small>Aggiornamento ufficiale 12 min fa</small></span></div><div class="signal" style="margin-top:8px"><span class="signal-icon">!</span><span><b>Inter · Lineup</b><small>3 fonti in convergenza</small></span></div></div></aside></section><section style="margin-top:22px"><div class="section-head"><h2>Club Serie A</h2><button class="link-btn" data-route="clubs">Apri tutti →</button></div><div class="grid club-grid">${CLUBS.slice(0,10).map(c=>`<article class="card club-card" data-club="${c.name}"><div class="club-top">${logo(c)}${c.breaking?'<span class="pulse" title="Breaking"></span>':''}</div><h3>${c.name}</h3><p>${c.news} nuove · aggiornato ${c.updated}</p></article>`).join('')}</div></section>`}

function clubs(){return `${head('Club intelligence','Club Serie A','Seleziona un club per aprire il dossier quotidiano.') }<div class="grid club-grid">${CLUBS.map(c=>`<article class="card club-card" data-club="${c.name}"><div class="club-top">${logo(c)}${c.breaking?'<span class="pulse" title="Breaking"></span>':''}</div><h3>${c.name}</h3><p>${c.news} nuove · aggiornato ${c.updated}</p></article>`).join('')}</div>`}
function brief(){return `${head('Executive digest','Morning Brief','Sintesi editoriale demo generata su segnali simulati e ordinata per priorità.')}<div class="grid two-col"><section class="card"><div class="section-head"><h2>Top stories</h2><span class="tag reported">8 min read</span></div>${NEWS.slice(0,5).map(newsItem).join('')}</section><aside class="stack"><div class="card"><h2 style="margin-top:0">Cosa monitorare oggi</h2><div class="signal-list"><div class="signal"><span class="signal-icon">1</span><span><b>Rifinitura Napoli</b><small>Decisione sul terzino</small></span></div><div class="signal"><span class="signal-icon">2</span><span><b>Conferenza Roma</b><small>Ore 14:00</small></span></div><div class="signal"><span class="signal-icon">3</span><span><b>Test Bologna</b><small>Esito atteso nel pomeriggio</small></span></div></div></div><div class="card"><h2 style="margin-top:0">Sentiment stampa</h2><div class="metric-value">+12</div><p class="subhead">Leggermente positivo · indicatore demo</p><div class="consensus" style="margin-top:18px">${'<i class="on"></i>'.repeat(4)}<i></i></div></div></aside></div>`}
function news(){return `${head('Cross-club monitor','News Feed','Tutte le segnalazioni demo, filtrabili per stato e tema.')}<div class="filters">${['All','Official','Reported','Rumour','Injuries','Probable XI','Players'].map(f=>`<button class="filter-btn ${state.filter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div><section class="card" id="feed">${visibleNews().length?visibleNews().map(newsItem).join(''):`<div class="empty-state"><strong>Nessun risultato</strong><p>Prova un altro filtro o intervallo temporale.</p></div>`}</section>`}
function match(){return `${head('Next fixture','Match Intelligence','Contesto pre-partita e segnali tattici simulati.')}<div class="grid dashboard-grid"><div class="stack"><section class="card match-card"><div class="team-lockup"><div class="team-logo-lg">NAP</div><b>Napoli</b><small>4-3-3</small></div><div class="versus"><small>DOM · 20:45</small><strong>VS</strong><small>Maradona</small></div><div class="team-lockup"><div class="team-logo-lg">JUV</div><b>Juventus</b><small>4-2-3-1</small></div></section><section class="card"><div class="section-head"><h2>Match signals</h2><span class="tag reported">Demo</span></div>${NEWS.filter(n=>['Match','Tactics','Probable XI'].includes(n.topic)).map(newsItem).join('')}</section></div><aside class="stack"><div class="card"><h2 style="margin-top:0">Availability</h2><div class="signal-list"><div class="signal"><span class="signal-icon">✓</span><span><b>Napoli</b><small>21 disponibili · 3 dubbi</small></span></div><div class="signal"><span class="signal-icon">✓</span><span><b>Juventus</b><small>22 disponibili · 1 dubbio</small></span></div></div></div><div class="card"><h2 style="margin-top:0">Tactical confidence</h2><div class="metric-value">82%</div><p class="subhead">Consensus su sistemi iniziali</p></div></aside></div>`}
function injuries(){let rows=[['Buongiorno','Napoli','Affaticamento','Valutazione','Alta'],['Castro','Bologna','Caviglia','In dubbio','Media'],['De Ketelaere','Atalanta','Gestione carichi','Parziale','Bassa'],['Gatti','Juventus','Contusione','Recupero','Media'],['Pellegrini','Roma','Muscolare','Out','Alta']];return `${head('Medical desk','Injuries','Stato medico riportato nelle fonti demo. Non è informazione sanitaria ufficiale.')}<section class="card table-wrap"><table class="data-table"><thead><tr><th>Giocatore</th><th>Club</th><th>Problema</th><th>Status</th><th>Impatto</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td class="${r[4]==='Alta'?'risk-high':r[4]==='Media'?'risk-mid':''}">${r[4]}</td></tr>`).join('')}</tbody></table></section>`}
function lineup(){return `${head('Formation forecast','Probabili formazioni Serie A','Fonte dichiarata e accesso diretto alla pagina originale.')}<div class="grid dashboard-grid"><section class="card empty-state"><span class="tag reported">Connettore non configurato</span><h2>Fantacalcio.it</h2><p>Le formazioni non vengono inventate né copiate senza autorizzazione. Collega un feed o un’API consentita per mostrare modulo, titolari, ballottaggi e ultime dai campi.</p><a class="primary-btn button-link" href="https://www.fantacalcio.it/probabili-formazioni-serie-a" target="_blank" rel="noopener noreferrer">Apri la fonte originale ↗</a></section><aside class="card"><h2 style="margin-top:0">Stato della fonte</h2><div class="source-row"><span><b>Fantacalcio.it</b><small>Probabili formazioni Serie A</small></span><span class="risk-mid">Non collegata</span></div><div class="source-row"><span><b>Tipo</b><small>Probabile, non ufficiale</small></span></div><div class="source-row"><span><b>Adapter</b><small>FantacalcioLineupAdapter</small></span><span class="tag reported">Placeholder</span></div></aside></div>`}
function players(){return `${head('Squad monitor','Players','Profili demo ordinati per rilevanza editoriale nelle ultime 24 ore.')}<section class="card table-wrap"><table class="data-table"><thead><tr><th>Giocatore</th><th>Club</th><th>Ruolo</th><th>Trend score</th><th>Segnale</th><th></th></tr></thead><tbody>${PLAYERS.map(p=>{let active=state.watchlist.includes(p[0]);return `<tr><td><b>${p[0]}</b></td><td>${p[1]}</td><td>${p[2]}</td><td>${p[3]}</td><td>${p[4]}</td><td><button class="watch-btn ${active?'active':''}" data-watch="${p[0]}">${active?'★ Seguito':'☆ Segui'}</button></td></tr>`}).join('')}</tbody></table></section>`}
function watchlist(){let list=PLAYERS.filter(p=>state.watchlist.includes(p[0]));return `${head('Personal workspace','Watchlist','Le tue priorità, salvate sul dispositivo.')}${list.length?`<div class="grid club-grid">${list.map(p=>`<article class="card"><div class="club-top"><span class="club-logo">${p[0].split(' ').map(x=>x[0]).join('').slice(0,2)}</span><button class="watch-btn active" data-watch="${p[0]}">★</button></div><h3 style="margin-bottom:4px">${p[0]}</h3><p class="subhead">${p[1]} · ${p[2]}</p><div class="metric-value">${p[3]}</div><small class="metric-delta">Trend score demo</small></article>`).join('')}</div>`:`<div class="card empty-state"><strong>La watchlist è vuota</strong><p>Aggiungi giocatori dalla sezione Players. Le scelte resteranno salvate su questo dispositivo.</p><button class="primary-btn" data-route="players">Esplora giocatori</button></div>`}`}
function sources(){let ss=[['Club official channels','20 fonti','98%'],['National sports press','8 fonti','84%'],['Local correspondents','7 fonti','77%'],['Transfer networks','3 fonti','63%']];return `${head('Coverage map','Sources','Registry dimostrativo. Nessun feed reale è collegato in questa versione.')}<div class="grid two-col"><section class="card"><div class="section-head"><h2>Source registry</h2><span class="tag official">38 demo</span></div>${ss.map(s=>`<div class="source-row"><span><b>${s[0]}</b><small>${s[1]}</small></span><span class="reliability">${s[2]} reliability</span><button class="watch-btn" data-toast="Configurazione sorgente disponibile nel file config">Configura</button></div>`).join('')}</section><aside class="card"><h2 style="margin-top:0">Adapter status</h2><p class="subhead">La piattaforma usa un adapter demo locale. Nel file JavaScript trovi il punto di estensione per collegare un backend, RSS autorizzati o API editoriali.</p><div class="signal-list"><div class="signal"><span class="status-dot"></span><span><b>DemoAdapter</b><small>Attivo · dataset locale</small></span></div><div class="signal"><span style="width:8px;height:8px;border-radius:50%;background:var(--muted)"></span><span><b>LiveApiAdapter</b><small>Placeholder · non configurato</small></span></div></div></aside></div>`}
function archive(){return `${head('Historical intelligence','Archive','Navigazione dimostrativa dei briefing precedenti.')}<section class="card"><div class="filters"><button class="filter-btn active">Settembre 2026</button><button class="filter-btn">Agosto 2026</button><button class="filter-btn">Luglio 2026</button></div>${['24 settembre 2026','23 settembre 2026','22 settembre 2026','21 settembre 2026'].map((d,i)=>`<div class="source-row"><span><b>Morning Brief · ${d}</b><small>${214-i*9} articoli · 20 club</small></span><span class="reliability">${12-i} high-priority</span><button class="watch-btn" data-toast="Archivio demo aperto">Apri</button></div>`).join('')}</section>`}
function clubDetail(){let c=clubByName(state.club)||CLUBS[0],cn=NEWS.filter(n=>n.club===c.name),meta=window.SPI_SOURCES.clubs[c.name]||['—',[]],national=window.SPI_SOURCES.national;let chips=list=>`<div class="source-chip-grid">${list.map(s=>`<div class="source-chip"><b>${s}</b><small>Non collegata · accesso autorizzato richiesto</small></div>`).join('')}</div>`;return `${head('Club daily intelligence',c.name,`${meta[0]} · ${c.news} nuove segnalazioni · aggiornato ${c.updated}`)}<div class="club-tabs"><button class="filter-btn active">Panoramica</button><button class="filter-btn" data-route="news">Notizie</button><button class="filter-btn" data-route="lineup">Probabile formazione</button><button class="filter-btn" data-route="injuries">Infortuni</button></div><div class="grid dashboard-grid"><div class="stack"><section class="card"><div class="section-head"><h2>Riepilogo della mattina</h2>${logo(c)}</div><p class="subhead">Panoramica dimostrativa: comunicazioni ufficiali, notizie riportate e indiscrezioni sono sempre separate. La testata è dichiarata sopra ogni contenuto.</p></section><section class="card"><div class="section-head"><h2>Notizie del club</h2><span class="tag reported">Dati demo</span></div>${cn.length?cn.map(newsItem).join(''):`<div class="empty-state"><strong>Nessuna notizia demo recente</strong><p>Configura le fonti autorizzate per questo club.</p></div>`}</section><section class="card"><div class="section-head"><h2>Testate monitorate</h2><span>${national.length+meta[1].length} fonti</span></div><h3 class="source-group-title">Nazionali</h3>${chips(national)}<h3 class="source-group-title">Locali · ${meta[0]}</h3>${chips(meta[1])}</section></div><aside class="stack"><div class="card"><h2 style="margin-top:0">Probabile formazione</h2><p class="subhead"><b>Fonte prevista: Fantacalcio.it</b><br>Connettore autorizzato non configurato.</p><button class="primary-btn" data-route="lineup">Apri formazione</button></div><div class="card"><h2 style="margin-top:0">Argomenti</h2>${['Disponibilità','Probabile XI','Tattica','Mercato'].map((x,i)=>`<div style="margin:16px 0"><div class="news-meta"><b style="color:var(--text)">${x}</b><span class="score">${88-i*9}</span></div><div class="consensus" style="margin-top:7px">${'<i class="on"></i>'.repeat(4-i%2)}<i></i></div></div>`).join('')}</div><button class="primary-btn" data-route="clubs">← Tutte le squadre</button></aside></div>`}

const views={home,brief,news,match,injuries,lineup,players,watchlist,sources,archive,clubs,club:clubDetail};
function render(){renderNav();app.innerHTML=(views[state.route]||home)();app.focus({preventScroll:true});document.querySelector('#sidebar').classList.remove('open')}
function route(id){state.route=id;location.hash=id;render()}
function toast(msg){let t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function openNews(id){let n=NEWS.find(x=>x.id===Number(id));detailContent.innerHTML=`${badge(n.type)}<h2>${n.title}</h2><div class="news-meta"><span>${n.club}</span><span>·</span><span>${n.source}</span><span>·</span><span>${n.time}h fa</span></div><p>${n.summary}</p><div class="card" style="margin-top:18px"><b>Source Consensus</b><p>${n.type==='Official'?'Pubblicazione diretta del club.':n.type==='Reported'?'Conferma simulata da più fonti editoriali.':'Segnalazione preliminare non confermata.'}</p><div class="consensus">${Array.from({length:5},(_,i)=>`<i class="${i<Math.round(n.score/20)?'on':''}"></i>`).join('')}</div></div><div class="modal-actions"><button class="primary-btn" data-close>Chiudi</button></div>`;detailModal.hidden=false}
function doSearch(q){let low=q.toLowerCase().trim();if(!low){searchResults.innerHTML='<p class="empty-copy">Inizia a digitare per cercare club, giocatori e intelligence.</p>';return}let results=[...CLUBS.filter(c=>c.name.toLowerCase().includes(low)).map(c=>({title:c.name,meta:'Club',action:`club:${c.name}`})),...PLAYERS.filter(p=>p[0].toLowerCase().includes(low)||p[1].toLowerCase().includes(low)).map(p=>({title:p[0],meta:`${p[1]} · Giocatore`,action:'players'})),...NEWS.filter(n=>(n.title+' '+n.summary+' '+n.club).toLowerCase().includes(low)).map(n=>({title:n.title,meta:`${n.club} · ${n.type}`,action:`news:${n.id}`}))].slice(0,10);searchResults.innerHTML=results.length?results.map(r=>`<div class="search-result" data-search-action="${r.action}"><span>${r.title}</span><small>${r.meta}</small></div>`).join(''):'<p class="empty-copy">Nessun risultato nel dataset demo.</p>'}

document.addEventListener('click',e=>{let r=e.target.closest('[data-route]');if(r)route(r.dataset.route);let c=e.target.closest('[data-club]');if(c){state.club=c.dataset.club;route('club')}let f=e.target.closest('[data-filter]');if(f){state.filter=f.dataset.filter;render()}let n=e.target.closest('[data-news]');if(n)openNews(n.dataset.news);let w=e.target.closest('[data-watch]');if(w){let p=w.dataset.watch;state.watchlist=state.watchlist.includes(p)?state.watchlist.filter(x=>x!==p):[...state.watchlist,p];localStorage.setItem('spi-watchlist',JSON.stringify(state.watchlist));toast(state.watchlist.includes(p)?`${p} aggiunto alla watchlist`:`${p} rimosso dalla watchlist`);render()}let close=e.target.closest('[data-close]');if(close){searchModal.hidden=true;detailModal.hidden=true}let msg=e.target.closest('[data-toast]');if(msg)toast(msg.dataset.toast);let sr=e.target.closest('[data-search-action]');if(sr){let [kind,val]=sr.dataset.searchAction.split(':');searchModal.hidden=true;if(kind==='club'){state.club=val;route('club')}else if(kind==='news')openNews(val);else route(kind)}});
document.querySelector('#menuBtn').onclick=()=>sidebar.classList.toggle('open');
document.querySelector('#themeBtn').onclick=()=>{let theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;localStorage.setItem('spi-theme',theme)};
document.documentElement.dataset.theme=localStorage.getItem('spi-theme')||'dark';
document.querySelector('#searchTrigger').onclick=()=>{searchModal.hidden=false;setTimeout(()=>globalSearch.focus(),0)};
document.querySelector('#globalSearch').oninput=e=>doSearch(e.target.value);
document.querySelector('#timeFilter').onchange=e=>{state.hours=e.target.value;render();toast(`Intervallo aggiornato: ${e.target.options[e.target.selectedIndex].text}`)};
document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.hidden=true}));
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchModal.hidden=false;globalSearch.focus()}if(e.key==='Escape'){searchModal.hidden=true;detailModal.hidden=true}});
window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'home';render()});
fetch('data/latest.json').then(r=>r.ok?r.json():null).then(data=>{if(data){automationStatus=data;render()}}).catch(()=>{});
render();

// Future data integration contract. Replace DemoAdapter with a backend endpoint.
window.PressIntelligenceAdapters={DemoAdapter:{async getClubs(){return CLUBS},async getNews(){return NEWS}},LiveApiAdapter:{baseUrl:'',async getClubs(){throw new Error('Live API non configurata')},async getNews(){throw new Error('Live API non configurata')}}};
